---
title: "Create Walkover of Brief Names"
author: "Sarah Torrence"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F, error = F)

# Box access
library(boxr)
box_auth()

# data manip
library(tidyverse)

# parallel processing
library(R.utils)
library(doParallel)

# data
# regressions/data for Amicus IV regressions/Amicus Author Organization Categorization.xlsx
brief_info <- box_read("936715223606")

# data/processed amicus files/amicus_text_512.csv
amicus <- box_read("937207017356")

# data/author and amicus measures/amicus-level-measures.csv
author_level <- box_read("861296487195")
```

Set the working directory for files to gets IDs for.

```{r}
box_setwd("99209523670")
```

```{r}
# Get the IDs of all the case folders 
case_folders <- box_ls() %>%
  as.data.frame() %>% 
  filter(type == "folder") %>% 
  rename(case = name)

case_folders %>% head(1)
```

For all of the folders, retrieve every file name and ID. 

```{r}
# number of cores available
n_cores <- detectCores() - 1
registerDoParallel(n_cores)

# given a df of ids for SC folder, extract names and ids of all files in case folder
# then, save
all_file_names <- function(case_folder_ids) {
  
  # get info for all files contained in each case folder
  # stored in a list of lists
  cases_ids_list <- mclapply(case_folder_ids$id,
                                box_ls,
                                mc.cores = n_cores)
  
  # convert to list of df
  cases_ids_list <- map(cases_ids_list, as.data.frame)
  
  # get name of folder (this is case name)
  cases_ids_list <- lapply(cases_ids_list, function(x) transform(x, case = sub(".*/", "", path)))
  
  print("Created list of dfs; each element is a case folder")
  
  # create iterator that will go through list element by element
  it <- iter(cases_ids_list, by = "row")
  
  # in each case folder, grab the name and id of the decision file
  file_ids <-
    foreach(i = it,
            .combine = rbind,
            .inorder = F) %dopar% {
              i %>%
                filter(grepl("amicus|amici", name, ignore.case = T)) %>%
                select(case, name, id)
            }
  print("Obtained amicus file ids")
  
  return(file_ids)
}

amicus_file_ids <- all_file_names(case_folders)

doParallel::stopImplicitCluster()
```

Join the different brief names into one dataframe.

```{r}
join_data <- author_level %>% select(id = BoxFileID, name_incorrect = AmicusBrief, CaseId)
join_data$id <- as.character(join_data$id)

join_data2 <- amicus_file_ids %>% select(id, name_correct = name)

data <- left_join(join_data, join_data2, by = c("id"))
```

```{r}
table(is.na(data$name_correct))
```

```{r}
data %>% filter(is.na(name_correct))
```

```{r}
data[data$id == 592236091833,'name_correct'] <- 'Stenberg v Carhart. Amics Brief for Petitioner by Agudath Israel of America.docx'
```


Add our updated brief id

```{r}
amicus_current_ids <- amicus %>% select(brief, brief_id = id)
final <- data %>% 
  left_join(amicus_current_ids, c("name_correct" = "brief")) %>% 
  select(new_id=brief_id, name_correct, name_incorrect, old_id = id)

final %>% filter(is.na(new_id)) # this brief doesn't exist in our data ?
```


## June v Russo


Read in the June v Russo names from Holly's data file.

```{r}
jvr_incorrect <- box_read_excel("941695019313", sheet="final") 
#jvr_incorrect %>% head()
```

Get the "correct" june v russo brief names

```{r}
jvr_correct <- amicus %>% filter(grepl("June", brief)) %>%
  mutate(id = as.double(id)) %>% 
  select(new_id=id,name_correct=brief)
```


Join the two 

```{r}
jvr <- jvr_correct %>% left_join(jvr_incorrect, c("new_id"="brief_id"))

jvr <- jvr %>% 
  mutate(old_id = 0) %>% 
  select(new_id, name_correct, name_incorrect=amicus, old_id)
```

Add to final df

```{r}
final <- final %>% rbind(jvr) %>%
  distinct(new_id, name_correct, name_incorrect, old_id)
```


## Save

Write to csv

```{r}
box_write(data,
           file_name = "walkover_brief_names.csv",
           dir_id = 145990409196)
```

