---
title: "Paper Visualizations"
author: "Amanda Konet"
date: "`r date()`"
output:
  html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F, error = F)
library(tidyverse)
library(ggplot2)
library(interactions)
library(boxr)
library(stargazer)
library(stringi)
#box_auth()

#df <- box_read("949901868853", read_fun = readr::read_csv)
df <- read_csv("~/Box/Amicus IV/regressions/data for Amicus IV regressions/amicus-iv-regression-data-final-cases.csv") 
#amicus <- box_read("947307207905", read_fun = readr::read_csv)
```


# Figure 1 Number of Amici by Case

Data

```{r}
num_amici <- df %>% 
  distinct(year = lubridate::year(ddate2), cfemam, coppam) %>% 
  group_by(year) %>% 
  summarize(cfemam = mean(cfemam), coppam = mean(coppam))
```

Plot

```{r}
amici_ct_plt <- num_amici %>% 
  ggplot(., aes(x = year)) +
  geom_line(aes(y = cfemam, linetype = "Reproductive-Rights")) + 
  geom_line(aes(y = coppam, linetype = "Antiabortion")) + 
  scale_linetype_manual("Amici Type:", values=c("Reproductive-Rights" = 1,"Antiabortion" = 2)) + 
  coord_cartesian(ylim = c(0, 50)) +
  labs(
    x = "Decision Year",
    y = "Average Number of Amici",
    title = "Annual Average Number of Amici for Abortion Cases"
  ) + 
  theme_minimal() +
  theme(
    plot.title = element_blank(),
    title = element_text(size = 10, family = "Times New Roman"),
    legend.text = element_text(size = 10, family = "Times New Roman"),
    axis.text = element_text(size = 10, family = "Times New Roman"),
    legend.position = "bottom"
  )

ggsave("graphics/avg_amici_time.png",amici_ct_plt, height = 5, width = 8)
amici_ct_plt
```

Check spike
```{r}
df %>% filter(lubridate::year(ddate2) == 1989) %>% distinct(case, ddate2, cfemam, coppam)
```


# Table 1

```{r, results='asis'}
#transform dataframe
author_types <- amicus %>% select(chcauf, lifauo, medauf, medauo, legauf, legauo, relauf, relauo) %>%
  mutate(across(where(is.character), as.numeric)) %>%
  summarise(across(where(is.numeric), ~ sum(.x, na.rm = TRUE))) %>%
  pivot_longer(.,cols = c(chcauf, lifauo, medauf, medauo, legauf, legauo, relauf, relauo), names_to = "var", values_to = "ct") %>%
  arrange(var)

other_types <- amicus %>% select(forgau, antauo, govauf, govauo, sg, racauf, racauo, mpeauf, mpeauo, lg_bauf, forgauf, aclauf, aclauo, sgauf, sgauo) %>%
  mutate(across(where(is.character), as.numeric)) %>%
  summarise(across(where(is.numeric), ~ sum(.x, na.rm = TRUE))) %>%
  pivot_longer(.,cols = c(forgau, antauo, govauf, govauo, sg, racauf, racauo, mpeauf, mpeauo, lg_bauf, forgauf, aclauf, aclauo, sgauf, sgauo), names_to = "var", values_to = "ct") %>%
  arrange(var)

#clean up names
author_types <- author_types %>% mutate(author_type = substr(var, 1, 3), position = substr(var, 4, 6)) %>% select(-var)

author_types$position <- ifelse(author_types$position == "auf", 'Reproductive Rights', 'Antiabortion')
author_types <- author_types %>% mutate(`Amicus-Author Type` = case_when(
  author_type == 'chc' ~ 'Feminist Organizations',
  author_type == 'lif' ~ 'Prolife Organizations',
  author_type == 'med' ~ 'Medical Organizations',
  author_type == 'leg' ~ 'Legal Organizations',
  author_type == 'rel' ~ 'Religious Groups',
)) %>% select(-author_type)

#clean values
author_table <- author_types %>% pivot_wider(names_from = position, values_from = ct)
author_table[1,3] <- 0
author_table[3,2] <- 0

#create other category
other_types <- other_types %>% mutate(position = stri_sub(var,-1))
other_types$position <- ifelse(other_types$position == 'f', 'Reproductive Rights', 'Antiabortion')
other_types <- other_types %>% group_by(position) %>% summarize(ct = sum(ct))
other <- other_types %>% pivot_wider(names_from = position, values_from = ct)
author_table <- rbind(author_table, c("Other", other$`Reproductive Rights`, other$`Antiabortion`))

#add totals
total <- c("Total", 330, 441)
author_table <- rbind(author_table, total)

#manually order
author_table$order <- c(1, 4, 2, 3, 5, 6, 7)
author_table <- author_table %>% arrange(order) %>% select(-order)

#create table
stargazer(author_table, summary=FALSE, rownames=FALSE, title = "Table 1.  Total Number of Amicus Briefs by Amicus-Author Type in the Supreme Court Abortion Cases", notes = c("a. The “Other” category contains various additional types of amici, including for organizations focused on racial justice and LGBTQ rights and from the U.S. Solicitor General.", "b. The separate amicus categories do not sum to the column totals because amicus briefs can be counted in more than one category."), header=FALSE, type = 'html', notes.align = 'l', out = "graphics/table1.htm")
```

# Table A.1

```{r, results='asis'}
#read in models
forg_privacy <- readRDS("../modeling/amicus_type/models/forg_privacy.rds")
forg_privacy_interactions <- readRDS("../modeling/justicemq-interactions/models/forg_privacy_interactions.rds")
forg_undue <- readRDS("../modeling/amicus_type/models/forg_undue.rds")
forg_undue_interactions <- readRDS("../modeling/justicemq-interactions/models/forg_undue_interactions.rds")
lif_undue <- readRDS("../modeling/amicus_type/models/lif_undue.rds")
lif_undue_interactions <- readRDS("../modeling/justicemq-interactions/models/lif_undue_interactions.rds")
relauo_undue <- readRDS("../modeling/amicus_type/models/relauo_undue.rds")
relauo_undue_interactions <- readRDS("../modeling/justicemq-interactions/models/relauo_undue_interactions.rds")

stargazer(forg_privacy, forg_privacy_interactions,
          forg_undue, forg_undue_interactions,
          lif_undue, lif_undue_interactions,
          relauo_undue, relauo_undue_interactions,
          type='html',align=TRUE,
          model.numbers = F, ci=T,
          dep.var.labels="Justice Vote (1 = Fem)",
          column.labels = c("Model 1", "Model 2", 
                            "Model 3", "Model 4", "Model 5", "Model 6", 
                            "Model 7", "Model 8"),
          order=c("forgauf_privacy", "justicemq:forgauf_privacy",
                  "forgauf_undue_burden", "justicemq:forgauf_undue_burden",
                  "lifauo_undue_burden", "justicemq:lifauo_undue_burden",
                  "relauo_undue_burden", "justicemq:relauo_undue_burden",
                  "justicemq","justicefem","pfemam","poppam","sgfem3","lcdisdirfem"),
          covariate.labels = c("feminist org privacy","feminist org privacy X justice ideology",
                               "feminist org undue burden", "feminist org undue burden x justice ideology",
                               "prolife org undue burden", "prolife org undue burden x justice ideology",
                               "religious (AA) undue burden", "religious (AA) undue burden X justice ideology",
                               "justice ideology", "justice gender", "proportion RR", "proportion AA",
                               "SG amicus brief", "lower court decision"),
          out="graphics/table2.htm")
```

# Table A.2

```{r, results='asis'}
#read in models
forg_womenhealth <- readRDS("../modeling/amicus_type/models/forg_womenhealth.rds")
forg_womenhealth_interactions <- readRDS("../modeling/justicemq-interactions/models/forg_womenshealth_interactions.rds")
medauf_womenhealth <- readRDS("../modeling/amicus_type/models/medauf_womenhealth.rds")
medauf_womenhealth_interactions <- readRDS("../modeling/justicemq-interactions/models/medauf_womenshealth_interactions.rds")
forg_womenfuture <- readRDS("../modeling/amicus_type/models/forg_womenfuture.rds")
relauo_abortionregret <- readRDS("../modeling/amicus_type/models/relauo_abortionregret.rds")
forg_evidence <- readRDS("../modeling/amicus_type/models/forg_evidence.rds")
forg_evidence_interactions <- readRDS("../modeling/justicemq-interactions/models/forg_evidence_interactions.rds")
medauo_evidence <- readRDS("../modeling/amicus_type/models/medauo_evidence.rds")
medauo_evidence_interactions <- readRDS("../modeling/justicemq-interactions/models/medauo_evidence_interactions.rds")

stargazer(forg_womenhealth, forg_womenhealth_interactions, 
          medauf_womenhealth, medauf_womenhealth_interactions,
          forg_womenfuture,
          relauo_abortionregret,
          forg_evidence, forg_evidence_interactions,
          medauo_evidence, medauo_evidence_interactions,
          title="Results", type='html',align=TRUE,
          model.numbers = F, ci=T,
          dep.var.labels="Justice Vote (1 = Fem)",
          column.labels = c("Model 1", "Model 2", 
                            "Model 3", "Model 4", "Model 5", "Model 6", 
                            "Model 7", "Model 8", "Model 9", "Model 10"),
          order=c("forgauf_womens_health", "justicemq:forgauf_womens_health",
                  "medauf_womens_health", "justicemq:medauf_womens_health",
                  "forgauf_womens_future_life",
                  "relauo_abortion_regret",
                  "forgauf_evidence", "justicemq:forgauf_evidence",
                  "medauo_evidence", "justicemq:medauo_evidence",
                  "justicemq","justicefem","pfemam","poppam","sgfem3","lcdisdirfem"),
          covariate.labels = c("feminist org women's health", "feminist org women's health X justice ideology",
                               "medical (RR) women's health", "medical (RR) women's health x justice ideology",
                               "feminist org women's futures",
                               "religious (AA) abortion regret", 
                               "feminist org expert evidence", "feminist org expert evidence X justice ideology",
                               "medical (RR) expert evidence", "medical (RR) expert evidence X justice ideology",
                               "justice ideology", "justice gender", "proportion RR", "proportion AA",
                               "SG amicus brief", "lower court decision"),
          out="graphics/table3.htm")
```

# Table A.3

```{r, results='asis'}
#read in models
forg_fetus <- readRDS("../modeling/amicus_type/models/forg_fetus.rds")
forg_morality <- readRDS("../modeling/amicus_type/models/forg_morality.rds")
relauo_fetus <- readRDS("../modeling/amicus_type/models/relauo_fetus.rds")
relauo_fetus_interactions <- readRDS("../modeling/justicemq-interactions/models/relauo_fetus_interactions.rds")
medauo_morality <- readRDS("../modeling/amicus_type/models/medauo_morality.rds")

stargazer(forg_fetus, forg_morality, relauo_fetus, relauo_fetus_interactions, medauo_morality,
          title="Results", type='html',align=TRUE,
          column.labels = c("Model 1", "Model 2", "Model 3", "Model 4", "Model 5"),
          model.numbers = F, ci=T,
          dep.var.labels="Justice Vote (1 = Fem)",
          order=c("forgauf_fetus",
                  "forgauf_morality_religion",
                  "relauo_fetus", "justicemq:relauo_fetus",
                  "medauo_morality_religion",
                  "justicemq","justicefem1","pfemam","poppam","sgfem3","lcdisdirfem1"),
          covariate.labels = c("feminist org fetus",
                               "feminist org morality and religious",
                               "religious (AA) fetus", "religious (AA) fetus X justice ideology",
                               "medical (RR) morality",
                               "justice ideology", "justice gender", "proportion RR", "proportion AA",
                               "SG amicus brief", "lower court decision"),
          out="graphics/table4.htm")
```

# Justice ideology graphs

```{r}
data <- #box_read(final_cases) %>% 
  read_csv("~/Box/Amicus IV/regressions/data for Amicus IV regressions/amicus-iv-regression-data-final-cases.csv") %>% 
  filter(justicevot != "NA") %>% 
  mutate(justicevot = as.numeric(justicevot),
         justiceid = as.factor(justiceid),
         justicefem = as.factor(justicefem),
         nonftyp2 = as.factor(nonftyp2),
         lcdisdirfem = ifelse(lcdisdirfem==1, 0, 1),
         lcdisdirfem = as.factor(lcdisdirfem),
         #sgfem3 = as.factor(sgfem3), 
         cirsplit = as.factor(cirsplit)) %>% 
  mutate(across(c(forgauf_abortion_regret:forgauf_womens_health,
                  legauf_abortion_regret:legauo_womens_health,
                  lifauo_abortion_regret:medauo_womens_health,
                  relauf_abortion_regret:relauo_womens_health,
                  fem_abortion_regret:opp_womens_health),
                ~replace_na(.x, 0))) %>% 
  filter(case != "Gonzales v PP")

# add case ID (second level var)
case_ids <- data %>% distinct(case) %>% arrange(case) %>% mutate(id = 1:n())
data <- case_ids %>% left_join(., data, by = "case")

# scale
data <- data %>%
  select(case:cirsplit, pfemam, poppam,
         forgauf_abortion_regret:forgauf_womens_health,
         legauf_abortion_regret:legauo_womens_health,
         lifauo_abortion_regret:medauo_womens_health,
         relauf_abortion_regret:relauo_womens_health,
         fem_abortion_regret:opp_womens_health) %>%  
  mutate(across(c(where(is.numeric), -justicevot, -id, -cirsplit, -sgfem3),
                ~(scale(., center=T, scale=T))))
```


## Forg

Privacy

```{r}
forg_privacy_plt <- 
  interact_plot(forg_privacy_interactions, pred = forgauf_privacy, modx = justicemq,
                #modx.values = c(-3.5, -1, 0, 1, 3.5),
                # random
                #modx.values = c(-1.65, -.55, -.08, .35, 1.5),
                # quantiles
                modx.values = c(-3.4, -.75, -.3, .59, 1.9),
                modx.labels = c("More Liberal", "Moderately Liberal","Moderate",
                                "Moderately Conservative", "More Conservative"),
                colors = c("blue", "gray", "lightskyblue", "darksalmon", "red"),
                #outcome.scale = "link",
                x.label = "Frame Frequency (Scaled)",
                y.label = "Probability of Voting in Favor of Repro-Rights",
                legend.main = "Justice Ideology") +
  theme_minimal() +
  theme(
    plot.title = element_blank(),
    title = element_text(size = 10, family = "Times New Roman"),
    legend.text = element_text(size = 10, family = "Times New Roman"),
    axis.text = element_text(size = 10, family = "Times New Roman"))

ggsave("graphics/forg_privacy.png", forg_privacy_plt, height = 5, width = 8)

forg_privacy_plt
```


Undue Burden

```{r}
forg_undue_plt <- 
  interact_plot(forg_undue_interactions, pred = forgauf_undue_burden, modx = justicemq,
                #modx.values = c(-3.5, -1, 0, 1, 3.5),
                # random
                #modx.values = c(-1.65, -.55, -.08, .35, 1.5),
                # quantiles
                modx.values = c(-3.4, -.75, -.3, .59, 1.9),
                modx.labels = c("More Liberal", "Moderately Liberal","Moderate",
                                "Moderately Conservative", "More Conservative"),
                colors = c("blue", "gray", "lightskyblue", "darksalmon", "red"),
                #outcome.scale = "link",
                x.label = "Frame Frequency (Scaled)",
                y.label = "Probability of Voting in Favor of Repro-Rights",
                legend.main = "Justice Ideology") +
  theme_minimal() +
  theme(
    plot.title = element_blank(),
    title = element_text(size = 10, family = "Times New Roman"),
    legend.text = element_text(size = 10, family = "Times New Roman"),
    axis.text = element_text(size = 10, family = "Times New Roman"))

ggsave("graphics/forg_undue.png", forg_undue_plt, height = 5, width = 8)

forg_undue_plt
```


Women's Health

```{r}
forg_health_plt <- 
  interact_plot(forg_womenhealth_interactions, pred = forgauf_womens_health, modx = justicemq,
                #modx.values = c(-3.5, -1, 0, 1, 3.5),
                # random
                #modx.values = c(-1.65, -.55, -.08, .35, 1.5),
                # quantiles
                modx.values = c(-3.4, -.75, -.3, .59, 1.9),
                modx.labels = c("More Liberal", "Moderately Liberal","Moderate",
                                "Moderately Conservative", "More Conservative"),
                colors = c("blue", "gray", "lightskyblue", "darksalmon", "red"),
                #outcome.scale = "link",
                x.label = "Frame Frequency (Scaled)",
                y.label = "Probability of Voting in Favor of Repro-Rights",
                legend.main = "Justice Ideology") +
  theme_minimal() +
  theme(
    plot.title = element_blank(),
    title = element_text(size = 10, family = "Times New Roman"),
    legend.text = element_text(size = 10, family = "Times New Roman"),
    axis.text = element_text(size = 10, family = "Times New Roman"))

ggsave("graphics/forg_health.png", forg_health_plt, height = 5, width = 8)

forg_health_plt
```


Evidence 

```{r}
forg_evidence_plt <- 
  interact_plot(forg_evidence_interactions, pred = forgauf_evidence, modx = justicemq,
                #modx.values = c(-3.5, -1, 0, 1, 3.5),
                # random
                #modx.values = c(-1.65, -.55, -.08, .35, 1.5),
                # quantiles
                modx.values = c(-3.4, -.75, -.3, .59, 1.9),
                modx.labels = c("More Liberal", "Moderately Liberal","Moderate",
                                "Moderately Conservative", "More Conservative"),
                colors = c("blue", "gray", "lightskyblue", "darksalmon", "red"),
                #outcome.scale = "link",
                x.label = "Frame Frequency (Scaled)",
                y.label = "Probability of Voting in Favor of Repro-Rights",
                legend.main = "Justice Ideology") +
  theme_minimal() +
  theme(
    plot.title = element_blank(),
    title = element_text(size = 10, family = "Times New Roman"),
    legend.text = element_text(size = 10, family = "Times New Roman"),
    axis.text = element_text(size = 10, family = "Times New Roman"))

ggsave("graphics/forg_evidence.png", forg_evidence_plt, height = 5, width = 8)

forg_evidence_plt
```

## RR Medical

Women's health

```{r}
medauf_health_plt <- 
  interact_plot(medauf_womenhealth_interactions, pred = medauf_womens_health, modx = justicemq,
                #modx.values = c(-3.5, -1, 0, 1, 3.5),
                # random
                #modx.values = c(-1.65, -.55, -.08, .35, 1.5),
                # quantiles
                modx.values = c(-3.4, -.75, -.3, .59, 1.9),
                modx.labels = c("More Liberal", "Moderately Liberal","Moderate",
                                "Moderately Conservative", "More Conservative"),
                colors = c("blue", "gray", "lightskyblue", "darksalmon", "red"),
                #outcome.scale = "link",
                x.label = "Frame Frequency (Scaled)",
                y.label = "Probability of Voting in Favor of Repro-Rights",
                legend.main = "Justice Ideology") +
  theme_minimal() +
  theme(
    plot.title = element_blank(),
    title = element_text(size = 10, family = "Times New Roman"),
    legend.text = element_text(size = 10, family = "Times New Roman"),
    axis.text = element_text(size = 10, family = "Times New Roman"))

ggsave("graphics/medauf_health.png", medauf_health_plt, height = 5, width = 8)

medauf_health_plt
```


## Prolife

Undue Burden

```{r}
lifauo_undue_plt <- 
  interact_plot(lif_undue_interactions, pred = lifauo_undue_burden, modx = justicemq,
                #modx.values = c(-3.5, -1, 0, 1, 3.5),
                # random
                #modx.values = c(-1.65, -.55, -.08, .35, 1.5),
                # quantiles
                modx.values = c(-3.4, -.75, -.3, .59, 1.9),
                modx.labels = c("More Liberal", "Moderately Liberal","Moderate",
                                "Moderately Conservative", "More Conservative"),
                colors = c("blue", "gray", "lightskyblue", "darksalmon", "red"),
                #outcome.scale = "link",
                x.label = "Frame Frequency (Scaled)",
                y.label = "Probability of Voting in Favor of Repro-Rights",
                legend.main = "Justice Ideology") +
  theme_minimal() +
  theme(
    plot.title = element_blank(),
    title = element_text(size = 10, family = "Times New Roman"),
    legend.text = element_text(size = 10, family = "Times New Roman"),
    axis.text = element_text(size = 10, family = "Times New Roman"))

ggsave("graphics/lifauo_undue.png", lifauo_undue_plt, height = 5, width = 8)

lifauo_undue_plt
```


## AA Medical

Expert-evidence

```{r}
medauo_evidence_plt <- 
  interact_plot(medauo_evidence_interactions, pred = medauo_evidence, modx = justicemq,
                #modx.values = c(-3.5, -1, 0, 1, 3.5),
                # random
                #modx.values = c(-1.65, -.55, -.08, .35, 1.5),
                # quantiles
                modx.values = c(-3.4, -.75, -.3, .59, 1.9),
                modx.labels = c("More Liberal", "Moderately Liberal","Moderate",
                                "Moderately Conservative", "More Conservative"),
                colors = c("blue", "gray", "lightskyblue", "darksalmon", "red"),
                #outcome.scale = "link",
                x.label = "Frame Frequency (Scaled)",
                y.label = "Probability of Voting in Favor of Repro-Rights",
                legend.main = "Justice Ideology") +
  theme_minimal() +
  theme(
    plot.title = element_blank(),
    title = element_text(size = 10, family = "Times New Roman"),
    legend.text = element_text(size = 10, family = "Times New Roman"),
    axis.text = element_text(size = 10, family = "Times New Roman"))

ggsave("graphics/medauo_evidence.png", medauo_evidence_plt, height = 5, width = 8)

medauo_evidence_plt
```


## AA Religious

Undue burden

```{r}
relauo_undue_plt <- 
  interact_plot(relauo_undue_interactions, pred = relauo_undue_burden, modx = justicemq,
                #modx.values = c(-3.5, -1, 0, 1, 3.5),
                # random
                #modx.values = c(-1.65, -.55, -.08, .35, 1.5),
                # quantiles
                modx.values = c(-3.4, -.75, -.3, .59, 1.9),
                modx.labels = c("More Liberal", "Moderately Liberal","Moderate",
                                "Moderately Conservative", "More Conservative"),
                colors = c("blue", "gray", "lightskyblue", "darksalmon", "red"),
                #outcome.scale = "link",
                x.label = "Frame Frequency (Scaled)",
                y.label = "Probability of Voting in Favor of Repro-Rights",
                legend.main = "Justice Ideology") +
  theme_minimal() +
  theme(
    plot.title = element_blank(),
    title = element_text(size = 10, family = "Times New Roman"),
    legend.text = element_text(size = 10, family = "Times New Roman"),
    axis.text = element_text(size = 10, family = "Times New Roman"))

ggsave("graphics/relauo_undue.png", relauo_undue_plt, height = 5, width = 8)

relauo_undue_plt
```


Fetus

```{r}
relauo_fetus_plt <- 
  interact_plot(relauo_fetus_interactions, pred = relauo_fetus, modx = justicemq,
                #modx.values = c(-3.5, -1, 0, 1, 3.5),
                # random
                #modx.values = c(-1.65, -.55, -.08, .35, 1.5),
                # quantiles
                modx.values = c(-3.4, -.75, -.3, .59, 1.9),
                modx.labels = c("More Liberal", "Moderately Liberal","Moderate",
                                "Moderately Conservative", "More Conservative"),
                colors = c("blue", "gray", "lightskyblue", "darksalmon", "red"),
                #outcome.scale = "link",
                x.label = "Frame Frequency (Scaled)",
                y.label = "Probability of Voting in Favor of Repro-Rights",
                legend.main = "Justice Ideology") +
  theme_minimal() +
  theme(
    plot.title = element_blank(),
    title = element_text(size = 10, family = "Times New Roman"),
    legend.text = element_text(size = 10, family = "Times New Roman"),
    axis.text = element_text(size = 10, family = "Times New Roman"))

ggsave("graphics/relauo_fetus.png", relauo_fetus_plt, height = 5, width = 8)

relauo_fetus_plt
```

